baseURL = "https://colinpaulish.github.io/cp_hugo_nz30/"
languageCode = "en-US"
title = "Colin Paulish"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/colin_paulish.png"
  author = "Colin Paulish"
  description = "Place to mix two passions: sustainability and data analysis."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  #Github        = "username"
  Email         = "colinpaulish@mail.com"
  #Twitter       = "username"
  LinkedIn      = "colin-paulish"
  #Stackoverflow = "username"
  #Medium        = "username"
  #Telegram      = "username"
  #RSS           = "/blog/index.xml"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  #name = "projects"
  #identifier = "projects"
  #weight = 200
  #url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
